name: NSE Screener

on:
  schedule:
    - cron: '30 14 * * 1-5'   # 8:00 PM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-screener:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yfinance pandas

      - name: Run Screener
        run: python scanner/main.py

      - name: Commit cmp
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add cmp.json
          git commit -m "Update NSE CMP data" || echo "No changes"
          git push
